# Generated by Django 4.2.1 on 2023-06-25 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_category_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='news_categories',
            new_name='categories',
        ),
    ]
