# Generated by Django 4.2.1 on 2023-06-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_link',
            field=models.URLField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='original_link',
            field=models.URLField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
