# Generated by Django 4.2.1 on 2023-06-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_original_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
