# Generated by Django 4.2.1 on 2023-06-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_link_2',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='source_link_3',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='source_link_4',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
