version: "3.9"

services:
    web:
        build: .
        command: sh -c "python /code/manage.py runserver 0.0.0.0:80"
        volumes:
            - .:/code
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on:
            - db
            - redis
    db:
        image: postgres:13
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=factoid
            - POSTGRES_PASSWORD=Factoid!23
            - POSTGRES_DB=factoid_dev
    redis:
        image: redis:6.2-alpine
        ports:
            - 6379:6379
volumes:
    postgres_data: