version: "3.9"

services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on:
            - db
    db:
        image: postgres:13
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=factoid
            - POSTGRES_PASSWORD=Factoid!23
            - POSTGRES_DB=factoid_dev
volumes:
    postgres_data: