# Generated by Django 4.2.1 on 2023-06-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_stockprofile_stock_cik_stock_cusip_stock_isin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(choices=[('ENER', 'Energy'), ('MAT', 'Materials'), ('IND', 'Industrials'), ('UTIL', 'Utilities'), ('HEALTH', 'Healthcare'), ('FIN', 'Financials'), ('DISC', 'Consumer Discretionary'), ('STAP', 'Consumer Staples'), ('IT', 'Technology'), ('COMM', 'Communication Services'), ('REAL', 'Real Estate')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
