# Generated by Django 4.2.1 on 2023-06-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_stock_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='isEtfOrFund',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ETF or Index Fund'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(choices=[('ENER', 'Energy'), ('MAT', 'Materials'), ('IND', 'Industrials'), ('UTIL', 'Utilities'), ('HEALTH', 'Healthcare'), ('FIN', 'Financials'), ('DISC', 'Consumer Discretionary'), ('STAP', 'Consumer Staples'), ('IT', 'Information Technology'), ('COMM', 'Communication Services'), ('REAL', 'Real Estate')], max_length=100, null=True),
        ),
    ]
