# Generated by Django 4.2.1 on 2023-06-21 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_alter_stock_firm_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StockAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.stock')),
            ],
        ),
        migrations.DeleteModel(
            name='StockProfile',
        ),
    ]
