# Generated by Django 4.2.1 on 2023-06-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_article_stockanalysis_delete_stockprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
