# Generated by Django 4.2.1 on 2023-06-23 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_alter_article_image_link_alter_article_original_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sector',
        ),
        migrations.AddField(
            model_name='article',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.stock'),
        ),
    ]
