# Generated by Django 4.2.1 on 2023-06-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_remove_article_sector_article_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
