# Generated by Django 4.2.1 on 2023-06-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_delete_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='firm_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
