# Generated by Django 4.2.1 on 2023-06-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_alter_stock_firm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='exchange',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
