# Generated by Django 4.2.1 on 2023-06-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_stockanalysis_exchange_stockanalysis_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='dividend_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='dividendps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='incomettm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='open',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='previousclose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='revenuettm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='sharesOutstanding',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='volume',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
