# Generated by Django 4.2.1 on 2023-06-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_stock_market_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockanalysis',
            name='sharesOutstanding',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
