# Generated by Django 4.2.1 on 2023-06-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0020_stockanalysis_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockanalysis',
            name='marketCap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockanalysis',
            name='sharesOutstanding',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockanalysis',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
