# Generated by Django 4.2.1 on 2023-06-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0022_alter_stockanalysis_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='eps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='pe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
